#pragma once

#undef  PRODUCT_ID
#define PRODUCT_ID    0x2480
#undef  MANUFACTURER
#define MANUFACTURER    YDKB
#undef  PRODUCT
#define PRODUCT    Y80-11900 Keyboard (FW_VER)
#define DYNAMIC_KEYMAP_LAYER_COUNT    6
#define FLASH_KEYMAP_COUNT    2
#define VIAL_KEYBOARD_UID    {0x2E, 0xE6, 0x0E, 0x23, 0x34, 0xEF, 0x99, 0x37}

#define DEBUG_ACTION

#undef  RGBLIGHT_LIMIT_VAL
#define RGBLIGHT_LIMIT_VAL    192
#undef  RGBLED_NUM
#define RGBLED_NUM    0
#define INDICATOR_NUM    3
#define INDICATOR_0_FUNCT    (1<<USB_LED_NUM_LOCK)
#define INDICATOR_1_FUNCT    (1<<USB_LED_CAPS_LOCK)
#define INDICATOR_2_FUNCT    (1<<USB_LED_SCROLL_LOCK)
