#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = 
{
  {
    {KC_ESCAPE, KC_GRAVE, KC_1, KC_F1, KC_F2, KC_F7, KC_F8, KC_2},
    {KC_Q, KC_A, KC_NONUS_BSLASH, KC_LGUI, KC_LCTRL, KC_LSHIFT, KC_CAPSLOCK, KC_TAB},
    {KC_3, KC_F3, KC_F4, KC_F5, KC_F9, KC_F10, KC_4, KC_F11},
    {KC_D, KC_E, KC_X, KC_SPACE, KC_LALT, KC_Z, KC_S, KC_W},
    {KC_5, KC_R, KC_T, KC_6, KC_F6, KC_F12, KC_7, KC_Y},
    {KC_H, KC_N, KC_B, KC_SPACE, KC_G, KC_V, KC_C, KC_F},
    {KC_U, KC_I, KC_8, KC_INSERT, KC_DELETE, KC_9, KC_0, KC_O},
    {KC_L, KC_RALT, KC_O, KC_COMMA, KC_K, KC_SPACE, KC_M, KC_J},
    {KC_P, KC_END, KC_HOME, KC_PGUP, KC_PGDOWN, KC_MINUS, KC_EQUAL, KC_LBRACKET},
    {KC_ENTER, KC_QUOTE, KC_RSHIFT, MO(1), KC_SLASH, KC_APPLICATION, KC_DOT, KC_SCOLON},
    {KC_BSLASH, KC_RBRACKET, KC_BSPACE, KC_SCROLLLOCK, KC_PSCREEN, KC_PAUSE, KC_KP_4, KC_KP_1},
    {KC_KP_0, KC_NO, KC_NO, KC_UP, KC_RIGHT, KC_DOWN, KC_LEFT, KC_BSLASH},
    {KC_KP_8, KC_KP_7, KC_NUMLOCK, KC_KP_SLASH, KC_KP_ASTERISK, KC_KP_MINUS, KC_KP_9, KC_KP_PLUS},
    {KC_NO, KC_NO, KC_KP_6, KC_KP_3, KC_KP_ENTER, KC_KP_DOT, KC_KP_2, KC_KP_5}
  },
  {
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_NO, KC_NO, KC_VOLU, KC_VOLU, KC_VOLD, KC_MUTE, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}
  },
};
